### ISSUE TITLE
Setup gulp to create dev and production versions of the application.

### ISSUE THREAD

**Issue by bbroeksema** [CVCEeu-dh/histograph#19]
Rationale: all js files are now served individually. There are many, and chrome can only use up to six tcp connections at the same time. (probably the similar restriction for other browsers).

Reference: https://github.com/google/web-starter-kit

Use the web starter kit as an template for setting up gulp supported development.

**Comment by danieleguido** [comment]
The [Gulpfile.js](https://github.com/CVCEeu-dh/histograph/blob/playground/gulpfile.js) has been added,  `gulp` default task copies, concatenates and minifies styles and scripts in a `client/dist` folder.
`gulp templates` command now pushes the angular templates in $templateCache, but there isn't any "watcher" on file changes yet (todo)

**Comment by danieleguido** [comment]
Production mode can now be enabled either by using NODE_ENV process env variable or  `env: 'production'` in settings.js module.
The list of js files to load is now stored in a [separate module](https://github.com/CVCEeu-dh/histograph/blob/playground/client/src/files.js) and can be loaded dynamically by both jade and gulp (so that the list of client javascript files are in sync and in the right order)
